apiVersion: apps/v1
kind: Deployment
metadata:
  name: internship-back
spec:
  selector:
    matchLabels:
      app: internship-back
  replicas: 1
  template:
    metadata:
      labels:
        app: internship-back
    spec:
      containers:
        - name: internship-back
          image: chxws/internshipback:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: internship-back-svc
spec:
  selector:
    app: internship-back
  ports:
  - protocol: TCP
    port: 8082
    targetPort: http
